// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuEaW6D-TNZDcXT22dgbbbTJ07_zetxoQ',
    appId: '1:771917885956:web:890e53a0fe3f8a7b453b51',
    messagingSenderId: '771917885956',
    projectId: 'doit-a4035',
    authDomain: 'doit-a4035.firebaseapp.com',
    databaseURL: 'https://doit-a4035-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doit-a4035.appspot.com',
    measurementId: 'G-RPD2Q2532E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx6jm_-j9C56pUqykCcaFIyA5ll88vXKM',
    appId: '1:771917885956:android:28495a0e58aca980453b51',
    messagingSenderId: '771917885956',
    projectId: 'doit-a4035',
    databaseURL: 'https://doit-a4035-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doit-a4035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5V-BusMspUFBNZKsR_h3iIK37A7WRSg0',
    appId: '1:771917885956:ios:b496cef735fe1c96453b51',
    messagingSenderId: '771917885956',
    projectId: 'doit-a4035',
    databaseURL: 'https://doit-a4035-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doit-a4035.appspot.com',
    androidClientId: '771917885956-v5s8o4mct73otovj9edqvtaih9fk37nt.apps.googleusercontent.com',
    iosClientId: '771917885956-p6t51veamjnlej539kjgga0odclscd25.apps.googleusercontent.com',
    iosBundleId: 'com.uoj.doit',
  );
}
